FROM us.kheeper.com/public/postgres-base:v0.2.0

ARG VERSION=1.14.1

RUN dnf install -y \
	caddy \
	&& dnf clean all \
	&& rm -rf /var/cache/* /var/lib/dnf /var/lib/pgsql /var/lib/caddy /var/log/* /tmp/* \
	&& rm -rf /run/dnf /run/lock /run/log

RUN firewall-offline-cmd --zone=public --add-port=80/tcp \
	&& firewall-offline-cmd --zone=public --add-port=443/tcp

RUN systemctl enable caddy
COPY Caddyfile.khtmpl /etc/caddy/Caddyfile.khtmpl

RUN curl -fLO https://github.com/openfga/openfga/releases/download/v${VERSION}/openfga_${VERSION}_linux_amd64.tar.gz \
	&& tar xzf openfga_${VERSION}_linux_amd64.tar.gz -C /usr/local/bin openfga \
	&& rm openfga_${VERSION}_linux_amd64.tar.gz

RUN useradd --system --no-create-home --shell /sbin/nologin --user-group --groups postgres openfga

COPY openfga.service /usr/lib/systemd/system/openfga.service
COPY openfga.env.khtmpl /etc/kheeper/openfga.env.khtmpl
COPY kheeper.conf /usr/lib/tmpfiles.d/kheeper-openfga.conf
RUN systemctl enable openfga

COPY openfga-scrape.json /etc/victoria-metrics/scrape.d/openfga.json
COPY grafana-dashboards/openfga.json /etc/grafana/dashboards/openfga.json

COPY schema.json /etc/kheeper/schema.d/openfga.json
COPY starter.d/database.json /etc/kheeper/starter.d/database.json

RUN bootc container lint
