d /var/lib/pgsql      0700 postgres postgres - -
d /var/lib/caddy      0750 caddy    caddy    - -
d /var/roothome/.ssh  0700 root     root     - -
r /var/roothome/.ssh/authorized_keys
C /var/roothome/.ssh/authorized_keys 0600 root root - -
