d /var/lib/pihole              0755 root root  - -
d /var/lib/pihole/etc-pihole   0750 root root  - -
d /var/lib/pihole/etc-dnsmasq  0750 root root  - -
d /var/lib/caddy               0750 caddy caddy - -
