d /var/lib/pgsql      0700 postgres postgres - -
d /var/lib/caddy      0750 caddy    caddy    - -
d /var/lib/forgejo    0750 git      git      - -
d /var/lib/act-runner         0750 act-runner act-runner - -
d /var/lib/act-runner/workdir 0750 act-runner act-runner - -
d /var/roothome/.ssh  0700 root     root     - -
r /var/roothome/.ssh/authorized_keys
C /var/roothome/.ssh/authorized_keys 0600 root root - -
