{
 "title": "Forgejo Overview",
 "tags": [ "forgejo" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(go_info{job=\"forgejo\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gitea_users{job=\"forgejo\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gitea_repositories{job=\"forgejo\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Metrics scrape rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(promhttp_metric_handler_requests_total{job=\"forgejo\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Process resident memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"forgejo\",instance=~\"$instance\"}"
    }
   ]
  }
 ]
}