# latest quay.io/fedora/fedora-bootc:44-x86_64
FROM quay.io/fedora/fedora-bootc@sha256:e85e3bc4823a22f98b7393a7ae53cd5138f8d4b150405edabc6515f4826e094c

RUN dnf makecache

RUN dnf install -y firewalld && systemctl enable firewalld
RUN firewall-offline-cmd --remove-service=dhcpv6-client \
	&& firewall-offline-cmd --remove-service=mdns \
	&& firewall-offline-cmd --remove-service=ssh \
	&& firewall-offline-cmd --zone=public --add-port=22/tcp

COPY admin.sysusers /usr/lib/sysusers.d/admin.conf
RUN useradd --uid 1000 --create-home --shell /bin/bash admin \
	&& rm -f /var/home/admin/.bash_logout /var/home/admin/.bash_profile /var/home/admin/.bashrc
COPY authorized_keys.khtmpl /usr/share/factory/var/home/admin/.ssh/authorized_keys.khtmpl
COPY ssh-files.conf /usr/lib/tmpfiles.d/kheeper-base.conf
COPY sshd.conf /etc/ssh/sshd_config.d/10-kheeper-base.conf
COPY admin.sudoers /etc/sudoers.d/admin
RUN chmod 0440 /etc/sudoers.d/admin
RUN passwd -l root

COPY journald.conf /etc/systemd/journald.conf.d/10-kheeper-base.conf

COPY schema.json /etc/kheeper/schema.d/base.json
