d /var/home/admin                       0700 admin admin - -
d /var/home/admin/.ssh                  0700 admin admin - -
r /var/home/admin/.ssh/authorized_keys
C /var/home/admin/.ssh/authorized_keys  0600 admin admin - -
