PermitRootLogin no
PasswordAuthentication no
PermitEmptyPasswords no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
GSSAPIAuthentication no
KerberosAuthentication no
HostbasedAuthentication no
UsePAM yes
PubkeyAuthentication yes
AuthenticationMethods publickey
AllowUsers admin
PermitUserEnvironment no
PermitTunnel no
AllowAgentForwarding no
AllowTcpForwarding no
AllowStreamLocalForwarding no
GatewayPorts no
X11Forwarding no
PrintMotd no
PrintLastLog yes
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 30
MaxAuthTries 3
MaxSessions 4
# PerSourcePenalties authfail:30s noauth:1s grace-exceeded:30s crash:90s refuseconnection:10m max:10m
Compression no
TCPKeepAlive no
Banner none

Match User admin
    AllowTcpForwarding local
    PermitOpen 127.0.0.1:* [::1]:*
